name: tamil_app
description: Tamil  - Professional Tamil Learning App for Schools
publish_to: 'none'
version: 2.0.0+2

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  shared_preferences: ^2.2.3
  google_fonts: ^8.1.0
  flutter_tts: ^4.2.5
  speech_to_text: ^7.4.0
  characters: ^1.3.0
  firebase_core: ^4.10.0
  firebase_auth: ^6.5.2
  google_sign_in: ^7.2.0
  cloud_firestore: ^6.5.0
  firebase_storage: ^13.4.2
  file_picker: ^11.0.2
  url_launcher: ^6.3.0
  confetti: ^0.8.0
  audioplayers: ^6.7.1
  http: ^1.2.0
  intl: ^0.20.2
  flutter_dotenv: ^6.0.1
  animations: ^2.0.11
  flutter_animate: ^4.5.0
  lottie: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
    - assets/data/tamil_proverbs.json
    - assets/data/v_thirukkural_list.json
    - .env

flutter_launcher_icons:
  android: true
  ios: false
  web:
    generate: true
    image_path: "assets/images/29099e40-2686-49d2-af50-5d939b785f80.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  image_path: "assets/images/29099e40-2686-49d2-af50-5d939b785f80.png"
  min_sdk_android: 21
